apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.80.10
  bindPort: 6443
nodeRegistration:
  name: k8s-master
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    cgroup-driver: systemd

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.30.14
networking:
  podSubnet: "10.244.0.0/16"

